### ISSUE TITLE
Print familiar error when *Qc_mask.nii.gz not found

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/luigi-pnlpipe#12]
Print a familiar error message when `*_mask.nii.gz` is found but not `*Qc_mask.nii.gz` because `mask_qc=True`:

```vim
Traceback (most recent call last):
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/worker.py", line 409, in check_complete
    is_complete = task.complete()
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 564, in complete
    outputs = flatten(self.output())
  File "/PHShome/tb571/Downloads/luigi-pnlpipe/workflows/struct_pipe.py", line 329, in output
    return local.path(pjoin(self.input()[0]['n4corr'].dirname, self.fs_dirname))
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 645, in input
    return getpaths(self.requires())
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 847, in getpaths
    return struct.__class__(getpaths(r) for r in struct)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 847, in <genexpr>
    return struct.__class__(getpaths(r) for r in struct)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 843, in getpaths
    return struct.output()
  File "/PHShome/tb571/Downloads/luigi-pnlpipe/workflows/struct_pipe.py", line 174, in output
    prefix= self.input()['aligned'].basename
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 645, in input
    return getpaths(self.requires())
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 843, in getpaths
    return struct.output()
  File "/PHShome/tb571/Downloads/luigi-pnlpipe/workflows/struct_pipe.py", line 145, in output
    ref_desc= glob(pjoin(self.input().dirname, self.ref_mask))[0]
IndexError: list index out of range
```

**Comment by tashrifbillah** [comment]
More of such:

```vim
Traceback (most recent call last):
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/worker.py", line 409, in check_complete
    is_complete = task.complete()
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 564, in complete
    outputs = flatten(self.output())
  File "/PHShome/tb571/Downloads/luigi-pnlpipe/workflows/struct_pipe.py", line 333, in output
    return local.path(pjoin(self.input()[0]['n4corr'].dirname, self.fs_dirname))
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 645, in input
    return getpaths(self.requires())
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 847, in getpaths
    return struct.__class__(getpaths(r) for r in struct)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 847, in <genexpr>
    return struct.__class__(getpaths(r) for r in struct)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 843, in getpaths
    return struct.output()
  File "/PHShome/tb571/Downloads/luigi-pnlpipe/workflows/struct_pipe.py", line 176, in output
    prefix= self.input()['aligned'].basename
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 645, in input
    return getpaths(self.requires())
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/luigi/task.py", line 843, in getpaths
    return struct.output()
  File "/PHShome/tb571/Downloads/luigi-pnlpipe/workflows/struct_pipe.py", line 156, in output
    mask_prefix= local.path(pjoin(self.input().dirname, prefix.split('_desc-')[0])+ '_desc-'+ desc)
UnboundLocalError: local variable 'desc' referenced before assignment
```
